# Generated by Django 5.2.1 on 2025-05-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='exemple@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='nom',
            field=models.CharField(default='Nom par défaut', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.TextField(),
        ),
    ]
