# Generated by Django 5.2.1 on 2025-05-12 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_client_email_client_nom_alter_client_adresse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='nom',
        ),
        migrations.AddField(
            model_name='produit',
            name='designation',
            field=models.CharField(default='Sans désignation', max_length=100),
        ),
        migrations.AddField(
            model_name='produit',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.fournisseur'),
        ),
        migrations.AddField(
            model_name='produit',
            name='reference',
            field=models.CharField(default='REF-000', max_length=100),
        ),
    ]
