# Generated by Django 5.2.1 on 2025-05-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_remove_produit_description_remove_produit_nom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.AddField(
            model_name='client',
            name='prenom',
            field=models.CharField(default='Prénom inconnu', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='tel',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.TextField(default='Adresse inconnue'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(default='Nom inconnu', max_length=100),
        ),
    ]
