# Generated by Django 5.2.1 on 2025-05-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_remove_client_user_client_prenom_client_tel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='user',
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='adresse',
            field=models.CharField(default='Adresse inconnue', max_length=255),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='email',
            field=models.EmailField(default='inconnu@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='libelle',
            field=models.CharField(default='Fournisseur inconnu', max_length=100),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='tel',
            field=models.CharField(default='0000000000', max_length=20),
        ),
    ]
