# Generated by Django 5.2.1 on 2025-05-14 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_fournisseur_entreprise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produit',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.fournisseur'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='reference',
            field=models.CharField(max_length=100),
        ),
    ]
