# Generated by Django 5.2.1 on 2025-05-19 18:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_produit_image_alter_produit_designation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='date',
            new_name='date_creation',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantite_entree',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantite_sortie',
        ),
        migrations.AddField(
            model_name='stock',
            name='emplacement',
            field=models.CharField(blank=True, default='Emplacement inconnu', max_length=200),
        ),
        migrations.AddField(
            model_name='stock',
            name='nom',
            field=models.CharField(default='Stock Principal', max_length=100),
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_entree', models.IntegerField(default=0)),
                ('quantite_sortie', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.produit')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.stock')),
            ],
        ),
    ]
