# Generated by Django 5.2.1 on 2025-05-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_rename_date_stock_date_creation_remove_stock_produit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='seuil',
            field=models.IntegerField(default=0, help_text='→ Alerte si quantité ≤ seuil'),
        ),
    ]
